# livecd-stage1 example specfile
# used to build a livecd-stage1

# The subarch can be any of the supported catalyst subarches (like athlon-xp).
# Refer to "man catalyst" or <https://wiki.gentoo.org/wiki/Catalyst>
# for supported subarches
# example:
# subarch: athlon-xp
subarch: amd64

# The version stamp is an identifier for the build.  It can be anything you wish
# it to be, but it is usually a date.
# example:
# version_stamp: 2006.1
version_stamp: xinnixos-xfce-latest

# The target specifies what target we want catalyst to do.  For building a CD,
# we start with livecd-stage1 as our target.
# example:
# target: livecd-stage1
target: livecd-stage1

# The rel_type defines what kind of build we are doing.  This is merely another
# identifier, but it useful for allowing multiple concurrent builds.  Usually,
# default will suffice.
# example:
# rel_type: default
rel_type: default

# This is the system profile to be used by catalyst to build this target.  It is
# specified as a relative path from /var/db/repos/gentoo/profiles.
# example:
# profile: default-linux/x86/2006.1
profile: default/amd64/17.1/desktop

# This specifies which snapshot to use for building this target.
# example:
# snapshot: 2006.1
snapshot_treeish: 6ff51302ea9f13e77fd33278988933ed09050b86

# This specifies where the seed stage comes from for this target,  The path is
# relative to $clst_sharedir/builds.  The rel_type is also used as a path prefix
# for the seed.
# example:
# default/stage3-x86-2006.1
source_subpath: default/stage3-amd64-desktop-openrc-latest.tar.xz

# This is an optional directory containing portage configuration files.  It
# follows the same syntax as /etc/portage and should be consistent across all
# targets to minimize problems.
# example:
# portage_confdir: /etc/portage
portage_confdir: /home/ben/catalyst/config/stages

# This option specifies the location of the ebuild repositories that you would
# like to have used when building this target. It takes a space-separated list
# of directory names.
# example:
# repos: /usr/local/portage
repos: /home/ben/catalyst/overlay/var/db/repos/edgets
      /home/ben/catalyst/overlay/var/db/repos/guru
      /home/ben/catalyst/overlay/var/db/repos/steam-overlay
     /home/ben/catalyst/overlay/var/db/repos/stha09
    /home/ben/catalyst/overlay/var/db/repos/tatsh-overlay

# This allows the optional directory containing the output packages for
# catalyst.  Mainly used as a way for different spec files to access the same
# cache directory.  Default behavior is for this location to be autogenerated
# by catalyst based on the spec file.
# example:
# pkgcache_path: /tmp/packages
#pkgcache_path:

# The livecd-stage1 target is where you will build packages for your CD.  These
# packages can be built with customized USE settings.  The settings here are
# additive to the default USE configured by the profile.  For building release
# media, the first thing we do is disable all default USE flags with -* and then
# begin to set our own.
# example:
# livecd/use: -* ipv6 socks5 livecd fbcon ncurses readline ssl
livecd/use: -aac
	compile-locales
	fbcon
	jpeg2k
	livecd
	networkmanager
	pulseaudio
	python
	-gpm
	flatpak
	bluetooth
	compat
	kde
	-gnome
	branding
	gtk
	plasma
	widgets
	fontconfig
	pcre32
	-systemd
	udev
	-eudev

# This is the set of packages that we will merge into the CD's filesystem.  They
# will be built with the USE flags configured above.  These packages must not
# depend on a configured kernel.  If the package requires a configured kernel,
# then it will be defined elsewhere.
# example:
# livecd/packages: livecd-tools dhcpcd acpid apmd gentoo-sources coldplug fxload irssi gpm syslog-ng parted links raidtools dosfstools nfs-utils jfsutils xfsprogs e2fsprogs reiserfsprogs ntfsprogs pwgen rp-pppoe screen mirrorselect penggy iputils hwdata-knoppix hwsetup lvm2 evms vim pptpclient mdadm ethtool wireless-tools prism54-firmware wpa_supplicant
livecd/packages: 
	app-accessibility/espeakup
	app-admin/hddtemp
	app-admin/sudo
	app-admin/syslog-ng
	app-admin/sysstat
	app-arch/bzip2
	app-arch/cpio
	app-arch/gzip
	app-arch/mt-st
	app-arch/p7zip
	app-arch/pbzip2
	app-arch/tar
	app-arch/zip
	app-arch/unrar
	app-backup/fsarchiver
	app-cdr/dvd+rw-tools
	app-cdr/cdrtools
	app-crypt/gnupg
	app-crypt/pinentry
	app-editors/nano
	app-editors/vim
	app-emacs/ebuild-mode
#	Fails to build...
#	app-emulation/xen-tools
	app-eselect/eselect-repository
	app-misc/colordiff
	app-misc/livecd-tools
	app-misc/mc
	app-misc/pax-utils
	app-misc/screen
	app-misc/tmux
	app-misc/wipe
	app-portage/cpuid2cpuflags
	app-portage/eix
	app-portage/genlop
	app-portage/gentoolkit
	app-portage/mirrorselect
	app-portage/portage-utils
	app-portage/pram
	app-portage/ufed
	app-shells/bash-completion
	app-shells/gentoo-bashcomp
	app-text/dos2unix
	app-text/ghostscript-gpl
	app-text/pdftk
	app-text/recode
	app-text/tree
	app-text/wgetpaste
	app-text/xournalpp
	app-vim/gentoo-syntax
	dev-lang/perl
	dev-lang/python
#	Gone until it supports python3_10
#	dev-util/kdevelop-python
	dev-vcs/git
	dev-vcs/subversion
	media-gfx/fbgrab
	media-gfx/gimp
	media-gfx/graphviz
	media-gfx/inkscape
	media-sound/alsa-utils
	net-analyzer/iptraf-ng
	net-analyzer/nmap
	net-analyzer/openbsd-netcat
	net-analyzer/tcpdump
	net-analyzer/tcptraceroute
	net-analyzer/traceroute
	net-dns/bind-tools
	net-fs/cifs-utils
	net-fs/nfs-utils
	net-ftp/ftp
	net-ftp/ncftp
	net-im/pidgin
	net-irc/hexchat
	net-irc/irssi
	net-misc/chrony
	net-misc/dhcpcd
	net-misc/iputils
	net-misc/ndisc6
	net-misc/openssh
	net-misc/rdate
	net-misc/rdesktop
	net-misc/rsync
	net-misc/vconfig
	net-misc/wget
	net-misc/whois
	net-vpn/networkmanager-openvpn
	net-vpn/networkmanager-pptp
	net-vpn/openfortivpn
	net-vpn/openvpn
	net-wireless/b43-fwcutter
	net-wireless/iw
	net-wireless/wireless-tools
	net-wireless/wpa_supplicant
	sys-apps/arch-chroot
	sys-apps/acl
	sys-apps/attr
	sys-apps/busybox
	sys-apps/cciss_vol_status
	sys-apps/chname
	sys-apps/coreutils
	sys-apps/dcfldd
	sys-apps/diffutils
	sys-apps/dmidecode
	sys-apps/dstat
	sys-apps/ethtool
	sys-apps/file
	sys-apps/findutils
	sys-apps/flashrom
	sys-apps/fxload
	sys-apps/gawk
	sys-apps/gptfdisk
	sys-apps/hdparm
	sys-apps/hwinfo
	sys-apps/ipmitool
	sys-apps/iproute2
	sys-apps/inxi
	sys-apps/less
	sys-apps/man-db
	sys-apps/man-pages
	sys-apps/man-pages-posix
	sys-apps/memtester
	sys-apps/memtest86+
	sys-apps/mlocate
	sys-apps/netplug
	sys-apps/nvme-cli
	sys-apps/pciutils
	sys-apps/sdparm
	sys-apps/sed
	sys-apps/setserial
	sys-apps/sg3_utils
	sys-apps/smartmontools
	sys-apps/which
	sys-apps/usbutils
	sys-apps/util-linux
	sys-auth/ssh-import-id
	sys-block/aoetools
	sys-block/fio
	sys-block/gparted
	sys-block/mtx
	sys-block/open-iscsi
	sys-block/parted
	sys-block/partimage
	sys-block/tw_cli
	sys-block/whdd
	sys-boot/grub
	sys-boot/os-prober
	sys-fs/bcache-tools
	sys-fs/btrfs-progs
	sys-fs/ddrescue
	sys-fs/dosfstools
	sys-fs/e2fsprogs
	sys-fs/exfat-utils
	sys-fs/extundelete
	sys-fs/fuse-exfat
	sys-fs/f2fs-tools
	sys-fs/genfstab
	sys-fs/growpart
	sys-fs/lsscsi
	sys-fs/lvm2
	sys-fs/mac-fdisk
	sys-fs/ntfs3g
	sys-fs/xfsprogs
	sys-kernel/linux-firmware
	sys-libs/gpm
	sys-power/acpid
	sys-process/htop
	sys-process/lsof
	sys-process/iotop
	sys-process/procps
	sys-process/psmisc
	www-client/firefox-bin
	x11-misc/lightdm-gtk-greeter
	x11-misc/lightdm
	xfce-base/thunar-volman
	xfce-extra/thunar-archive-plugin
	xfce-extra/thunar-media-tags-plugin
	xfce-extra/xfce4-mailwatch-plugin
	xfce-extra/xfce4-pulseaudio-plugin
	xfce-extra/xfce4-weather-plugin
	xfce-extra/xfce4-whiskermenu-plugin
	x11-misc/xdg-user-dirs
	x11-misc/prime-run
	x11-misc/plank
	sys-process/htop
	sys-process/cronie
	net-wireless/blueman
	net-wireless/bluez
	net-print/cups
	net-print/gutenprint
	net-print/hplip
	app-admin/system-config-printer
	net-misc/ntp
	net-im/discord
	net-fs/samba
	media-sound/pavucontrol
	media-fonts/terminus-font
	gnome-extra/nm-applet
	gnome-base/gvfs
	app-arch/engrampa
	app-admin/syslog-ng
	app-admin/gentoo_update
	app-admin/conky
	xfce-base/xfce4-meta
	dev-qt/qtstyleplugins
	media-video/vlc
	mail-client/thunderbird-bin
	app-admin/calamares
	x11-themes/adwaita-icon-theme
	x11-themes/gtk-engines-adwaita
	games-util/steam-meta
	kde-plasma/kwin
	kde-plasma/systemsettings
	kde-plasma/kde-gtk-config
	media-gfx/flameshot
	media-fonts/jetbrains-mono
	media-fonts/jetbrainsmono-nerdfont
        kde-misc/kwin-effects-cube
	kde-plasma/plasma-workspace
	kde-plasma/plasma-desktop
	net-wireless/broadcom-sta
	app-emulation/spice-vdagent
	dev-qt/qtwebengine
	app-misc/neofetch
