subarch: amd64
version_stamp: stormgenz-09-01-2024
target: livecd-stage1
rel_type: default
profile: default/linux/amd64/23.0/desktop
snapshot_treeish: c34f7dd28806f83646e35a497a6e48f777e9de3c
source_subpath: default/stage3-amd64-openrc-latest.tar.xz
compression_mode: pixz
portage_confdir: /home/bennji/catalyst_stormgenz/config/stages
repos: /home/bennji/catalyst_stormgenz/root_overlay/var/db/repos/guru
/home/bennji/catalyst_stormgenz/root_overlay/var/db/repos/tezeta
/home/bennji/catalyst_stormgenz/root_overlay/var/db/repos/tatsh-overlay
/home/bennji/catalyst_stormgenz/root_overlay/var/db/repos/edgets
/home/bennji/catalyst_stormgenz/root_overlay/var/db/repos/steam-overlay

livecd/use:
	-aac
	compile-locales
	fbcon
	jpeg2k
	livecd
	networkmanager
	openexr
	opus
	postproc
	portaudio
	pulseaudio
	python
	vpx
	xetex
	compat
	branding
	plymouth
        widgets
	build
	-ruby31

livecd/packages:
	app-admin/hddtemp
	app-admin/sudo
	app-admin/syslog-ng
	app-admin/sysstat
	app-arch/bzip2
	app-arch/cpio
	app-arch/gzip
	app-arch/mt-st
	app-arch/p7zip
	app-arch/pbzip2
	app-arch/tar
	app-arch/zip
	app-arch/unrar
	app-backup/fsarchiver
	app-cdr/dvd+rw-tools
	app-cdr/cdrtools
	app-crypt/gnupg
	app-crypt/pinentry
	app-editors/nano
	app-editors/vim
	app-emacs/ebuild-mode
#	Fails to build...
#	app-emulation/xen-tools
	app-eselect/eselect-repository
	app-misc/livecd-tools
	app-misc/mc
	app-misc/pax-utils
	app-misc/tmux
	app-misc/wipe
	app-portage/cpuid2cpuflags
	app-portage/eix
	app-portage/genlop
	app-portage/gentoolkit
	app-portage/mirrorselect
	app-portage/portage-utils
	app-portage/pram
	app-portage/ufed
	app-shells/bash-completion
	app-shells/gentoo-bashcomp
	app-text/dos2unix
	app-text/ghostscript-gpl
	app-text/pdftk
	app-text/recode
	app-text/tree
	app-text/wgetpaste
	app-text/xournalpp
	app-vim/gentoo-syntax
	dev-lang/perl
	dev-lang/python
	dev-lang/ruby
	dev-ruby/bundler
	dev-ruby/em-websocket
#	Gone until it supports python3_10
#	dev-util/kdevelop-python
	dev-vcs/git
	dev-vcs/subversion
	media-gfx/fbgrab
	media-gfx/gimp
	media-gfx/graphviz
	media-gfx/inkscape
	media-sound/alsa-utils
	net-analyzer/openbsd-netcat
	net-ftp/ftp
	net-ftp/ncftp
	net-im/pidgin
	net-irc/hexchat
	net-irc/irssi
	net-misc/chrony
	net-misc/dhcpcd
	net-misc/iputils
	net-misc/ndisc6
	net-misc/openssh
	net-misc/rdate
	net-misc/rdesktop
	net-misc/rsync
	net-misc/vconfig
	net-misc/wget
	net-misc/whois
	net-vpn/networkmanager-openvpn
	net-vpn/networkmanager-pptp
	net-vpn/openfortivpn
	net-vpn/openvpn
	net-wireless/b43-fwcutter
	net-wireless/iw
	net-wireless/wireless-tools
	net-wireless/wpa_supplicant
	sys-apps/arch-chroot
	sys-apps/acl
	sys-apps/attr
	sys-apps/busybox
	sys-apps/cciss_vol_status
	sys-apps/chname
	sys-apps/coreutils
	sys-apps/dcfldd
	sys-apps/diffutils
	sys-apps/dmidecode
	sys-apps/dstat
	sys-apps/ethtool
	sys-apps/file
	sys-apps/findutils
	sys-apps/flashrom
	sys-apps/fxload
	sys-apps/gawk
	sys-apps/gptfdisk
	sys-apps/hdparm
	sys-apps/hwinfo
	sys-apps/ipmitool
	sys-apps/iproute2
	sys-apps/inxi
	sys-apps/less
	sys-apps/man-db
	sys-apps/man-pages
	sys-apps/man-pages-posix
	sys-apps/memtester
	sys-apps/memtest86+
	sys-apps/mlocate
	sys-apps/netplug
	sys-apps/nvme-cli
	sys-apps/pciutils
	sys-apps/sdparm
	sys-apps/sed
	sys-apps/setserial
	sys-apps/sg3_utils
	sys-apps/smartmontools
	sys-apps/which
	sys-apps/usbutils
	sys-apps/util-linux
	sys-auth/ssh-import-id
	sys-block/aoetools
	sys-block/gparted
	sys-block/mtx
	sys-block/open-iscsi
	sys-block/parted
	sys-block/partimage
	sys-block/tw_cli
	sys-block/whdd
	sys-boot/grub
	sys-boot/os-prober
	sys-fs/bcache-tools
	sys-fs/btrfs-progs
	sys-fs/ddrescue
	sys-fs/dosfstools
	sys-fs/e2fsprogs
	sys-fs/exfat-utils
	sys-fs/extundelete
	sys-fs/fuse-exfat
	sys-fs/f2fs-tools
	sys-fs/genfstab
	sys-fs/growpart
	sys-fs/lsscsi
	sys-fs/lvm2
	sys-fs/mac-fdisk
	sys-fs/ntfs3g
	sys-fs/xfsprogs
	sys-kernel/linux-firmware
	sys-libs/gpm
	sys-power/acpid
	sys-process/htop
	sys-process/lsof
	sys-process/iotop
	sys-process/procps
	sys-process/psmisc
	www-client/firefox-bin
	x11-misc/lightdm-gtk-greeter
	x11-misc/lightdm
 	gnome-base/gnome-common
  	sys-auth/polkit
   	sys-auth/polkit-gnome
	xfce-base/thunar-volman
	xfce-extra/thunar-archive-plugin
	xfce-extra/thunar-media-tags-plugin
	xfce-extra/xfce4-mailwatch-plugin
	xfce-extra/xfce4-pulseaudio-plugin
	xfce-extra/xfce4-weather-plugin
	xfce-extra/xfce4-whiskermenu-plugin
	xfce-extra/xfce4-docklike-plugin
	xfce-extra/xfce4-panel-profiles
	x11-misc/xdg-user-dirs
	sys-process/htop
	sys-process/cronie
	net-wireless/blueman
	net-wireless/bluez
	net-print/cups
	net-print/gutenprint
	net-print/hplip
	app-admin/system-config-printer
	net-misc/ntp
	net-fs/samba
	media-sound/pavucontrol
	media-fonts/terminus-font
	gnome-extra/nm-applet
	gnome-base/gvfs
	app-arch/engrampa
	app-admin/syslog-ng
 	xfce-base/xfce4-meta
	dev-qt/qtstyleplugins
	media-video/vlc
	x11-themes/adwaita-icon-theme
	x11-themes/gtk-engines-adwaita
 	media-gfx/flameshot
	media-fonts/jetbrains-mono
	media-fonts/nerdfonts
	net-wireless/broadcom-sta
	app-emulation/spice-vdagent
	dev-qt/qtwebengine
	app-misc/fastfetch
	app-admin/calamares
	x11-themes/adw-gtk3
	x11-themes/tela-icon-theme
	x11-themes/arc-icon-theme
	media-fonts/ubuntu-font-family
	media-fonts/joypixels
	media-fonts/fontawesome
	media-fonts/corefonts
	x11-terms/alacritty
	x11-misc/picom
